import type { Metadata } from "next";
import Sidebar from "./_components/sidebar";
import Navbar from "./_components/navbar";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="  h-full">
      <div className=" inset-y-0 z-50 md:ml-56">
        <Navbar />
      </div>
      <div className=" hidden md:flex flex-col h-full w-56 fixed inset-y-0  z-50 border-r">
        <Sidebar />
      </div>
      <div className="md:pl-56">{children}</div>
    </div>
  );
}
